version: "3"
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
